category:
  url: 		/category/:slug
  class:	sfDoctrineRoute
  param: 	{ module: category, action: show }
  options:  { model: JobeetCategory, type: object }
job_show_user:
  url:     /job/:company_slug/:location_slug/:id/:position_slug
  class:   sfDoctrineRoute
  options:
    model: JobeetJob
    type:  object
    method_for_query: retrieveActiveJob
  param:   { module: job, action: show }
  requirements:
    id: \d+
    sf_method: [GET]

job:
  class:   sfDoctrineRouteCollection
  options: { model: JobeetJob }
 
# default rules
homepage:
  url:   /
  param: { module: job, action: index }
 
default_index:
  url:   /:module
  param: { action: index }
 
default:
  url:   /:module/:action/*
