<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/27 20:44:19
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
